### ISSUE TITLE
V2 : WinSW.NET2.exe not working

### ISSUE THREAD

**Issue by sparqueur** [kohsuke/winsw#181]
Hi,

It seems that "WinSW.NET2.exe" does not work.
When trying to install the service I get the following error : 

> To run this application, you first must install one of the following version of the .NET Framework:
> v4.0.30319

I am trying to install it with a 3.5 version.

Thanks in advance,

**Comment by oleg-nenashev** [comment]
Hmm, I'm pretty sure I was testing it before the release. But I see there are bootstrapper definitions for .NET 3.5: https://github.com/kohsuke/winsw/blob/master/src/Core/ServiceWrapper/winsw.csproj#L94-L104.

Will try to retest ASAP

**Comment by maurokade** [comment]
Hi oleg, not sure it is related, but i´ll post here before create a new one.
i had the winsw1 working fine on a windows7 machine
but the winsw2 shows the message:
"Unhandled Exception: System.BadImageFormatException: Could not load file or assembly 'x' or one of its dependencies. This assembly is built by a runtime newer than the currently loaded runtime and cannot be loaded."
for both WinSW.NET4 and WinSW.NET2
it is working fine on windows10
the win7 machine has .Net 3.5 and 4 installed

**Comment by oleg-nenashev** [comment]
Yes, it's likely related.
I'm still looking for a machine to reproduce the failures locally. My guess is that something is messed up within the AppVeyor build, because the local build seemed to work correctly in November.

I will have a limited internet access on the next 2 weeks, unfortunately. Will handle it as a top priority in late Jan. And I will appreciate PRs if somebody discovers the root cause earlier
