### ISSUE TITLE
Unable to start WIndows Service

### ISSUE THREAD

**Issue by ktlim86** [kohsuke/winsw#192]
Hi,

I am new to winsw and I have a problem trying to get the service started. I have managed to get the service installed but when I want to get it started, it generate an error message.
`
Windows could not start the SERVICE_NAME service on Local Computer.
Error 1053: The service did not respond to the start or control request in a timely fashion.
`

Below is the xml config file.
`
<service>
  <id>SERVICE_NAME</id>
  <name>SERVICE_NAME</name>
  <executable>java</executable>
  <arguments>-Xmx256m -jar "test-0.0.1-SNAPSHOT.jar"</arguments>
  <logmode>rotate</logmode>
</service>
`

The service that I want to install in run in Windows 2012 R2 and it is a domain client. Thanks

**Comment by oleg-nenashev** [comment]
Any errors in the wrapper/executable logs?

On Feb 20, 2017 12:04, "Kim Tee" <notifications@github.com> wrote:

Hi,

I am new to winsw and I have a problem trying to get the service started. I
have managed to get the service installed but when I want to get it
started, it generate an error message.
Windows could not start the SERVICE_NAME service on Local Computer. Error
1053: The service did not respond to the start or control request in a
timely fashion.

Below is the xml config file.
<service> <id>SERVICE_NAME</id> <name>SERVICE_NAME</name>
<executable>java</executable> <arguments>-Xmx256m -jar
"eureka-server-0.0.1-SNAPSHOT.jar"</arguments> <logmode>rotate</logmode>
</service>

The service that I want to install in run in Windows 2012 R2 and it is a
domain client. Thanks

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/kohsuke/winsw/issues/192>, or mute the thread

**Comment by ktlim86** [comment]
@oleg-nenashev there is no log generated and I am unable to pin point what went wrong.

**Comment by oleg-nenashev** [comment]
According to the code, there should be several log lines printed before the wrapper attempts to start the service. If the logs are not being generated, the working directory is not writable for the service user OR you may have disabled them via app.config 

Please provide the full console log at least.

The Error you reference likely means that your system cannot fully startup the service before the timeout. You can also try increasing the system-wide timeout. See the guide [here](https://support.threattracksecurity.com/support/solutions/articles/1000071019-error-1053-the-service-did-not-respond-in-a-timely-fashion-when-attempting-to-start-stop-or-pause)

**Comment by ktlim86** [comment]
@oleg-nenashev I have managed to resolve it by adding a app.exe.config as shown below.

`
<configuration>
      <startup>
        <supportedRuntime version="v4.0" />
      </startup>
      <runtime>
        <generatePublisherEvidence enabled="false"/> 
      </runtime>
    </configuration>
`
