### ISSUE TITLE
Hello Server is not a valid Win32 application. 

### ISSUE THREAD

**Issue by jjlauer** [kohsuke/winsw#34]
Having a difficult time getting any sort of service to start.  I can install my sample "Hello Server" service, but I get this error  in event viewer "The Hello Server service failed to start due to the following error: 
Hello Server is not a valid Win32 application. "

On the command-line, if I try to add a "start" argument, this is what shows up:

WMI.WmiException: UnknownFailure
   at WMI.WmiRoot.BaseHandler.CheckError(ManagementBaseObject result)
   at WMI.WmiRoot.InstanceHandler.Invoke(Object proxy, MethodInfo method, Object[] args)
   at WMI.Win32ServiceProxy.StartService()
   at winsw.WrapperService.Run(String[] _args)
   at winsw.WrapperService.Main(String[] args)

I'm trying this on Windows XP SP3 32-bit with the 1.16 release.  Wondering if there is any sort of debug I can turn on?  This is my config file:

<service>
  <id>hello-daemon</id>
  <name>Hello Server</name>
  <description>Demo daemon app</description>
  <executable>C:\Program Files\Java\jdk1.7.0_51\bin\java</executable>
  <arguments>-cp ..\lib* -Xrs com.mfizz.sample.HelloDaemon</arguments>
  <logmode>rotate</logmode>
  
  <log mode="reset"/>
  <workingdirectory>%BASE%..</workingdirectory>
</service>

**Comment by oleg-nenashev** [comment]
@jjlauer 
Have you resolved the issue according to comments from @cvarjao ?

**Comment by jjlauer** [comment]
No, it didn't work and I moved on to other solutions.

**Comment by oleg-nenashev** [comment]
I'm not sure that "The Hello Server service failed to start due to the following error:
Hello Server is not a valid Win32 application" is somehow related to WinSW. It's a common WinXP error when you build a program against new versions of WinAPI. Example: http://stackoverflow.com/questions/11305633/xxxxxx-exe-is-not-a-valid-win32-application

Other errors require a better analysis/debugging features in WinSW. I would start from moving WinSW to log4net and then imrpove the logging.

**Comment by oleg-nenashev** [comment]
Seems nothing to do here excepting the referenced issues
